export const routes = {
  learningBook: "/learning-book",
  start: "/start",
  eduda: "/eduda",
  app: "/app",
  info: "info",
  play: "play",
  main: "/",
  about: "/about",
  article: "/article",
  articleAdmin: "/admin-article",
  articleUpdate: "/admin-blog/:id",
  articleAdminList: "/admin-article-list",
  login: "/login",
  logout: "/logout",
  admin: "/admin",
  adminSong: "/admin/song",
  playlists: "/playlists",
  contacts: "/contacts",
};
