export const routes = {
  start: "/start",
  eduda: "/eduda",
  app: "/app",
  info: "info",
  play: "play",
  main: "/",
  about: "/about",
  blog: "/blog",
  blogPost: "/blog/:slug",
  blogAdmin: "/admin-blog",
  blogUpdate: "/admin-blog/:id",
  blogAdminList: "/admin-blog-list",
  login: "/login",
  logout: "/logout",
  admin: "/admin",
  adminSong: "/admin/song",
  playlists: "/playlists",
};
