export const routes = {
  start: "/start",
  eduda: "/eduda",
  app: "/app",
  info: "info",
  play: "play",
  main: "/",
  about: "/about",
  blog: "blog",
  login: "/login",
  logout: "/logout",
  admin: "/admin",
  adminSong: "/admin/song",
  playlists: "/playlists",
};
